### ISSUE TITLE
Are VMs with QNX OS supported?

### ISSUE THREAD

**Issue by HutzelFutzel** [naim94a/vix#13]
I am trying to write an process automation with a QNX VM for VMWare. I have the problem, that all actions (like `dir_exists()` and so on are leading to some kind of deadlock maybe? Or at least my Python process is still running but noch doing anything anymore after such function calls.

Also the output for vm.guest_os is "other-64"

Here is my code snippet

```
host = VixHost()    
try:
    vm = host.open_vm(r'C:\path\to\QNX_SDP.vmx')    
    vm.power_on()    
    vm.dir_exists(r'/home')
    vm.power_off()
except VixError as ex:
    print("Something went wrong :( {0}".format(ex))
```

**Comment by naim94a** [comment]
vix isn't aware of the underlying OS. 
`dir_exists` would only work if VMware Tools is installed (or maybe [open-vm-tools](https://github.com/vmware/open-vm-tools) for a *nix OS)

**Comment by HutzelFutzel** [comment]
Hm, maybe that is my problem. I will install VMWare Tools and see what happens.
