### ISSUE TITLE
How can i getting start with this package. The example of your first page is not working by me.

### ISSUE THREAD

**Issue by stein211** [naim94a/vix#4]

**Comment by naim94a** [comment]
Hi @stein211,
Would it be possible to provide more details about whats not working?

**Comment by stein211** [comment]
Hi @naim94a ,
sorry for my unclear question. I am trying to write the python script to manipulate my Visual Machine automatically. But i have no idea how to start. By the way, i use just VMWare Player.   I think i need a VixVM object. but for the Instructor i need get the handle first, which i don't know how can i get it. Or i should build the VixHost object first.   but it seems, that VixHost class don't has the function "connect()" any more.  Can you give me a short example that will be very helpful for me as new fish.  thanks again.

**Comment by naim94a** [comment]
First you need to create a VixHost object, connection is made by the constructor (for a VM on the local machine, no arguments are required).
After you have a VixHost object, you can call it's open_vm method to get a VixVM.
I'm not sure if the VIX API is implemented for VMware Player, it works for Workstation.

master branch's docs can be found at naim94a.github.io/vix

**Comment by stein211** [comment]
@naim94a 
thank u for the answer.  I have try this.

```
from vix import VixHost
host = VixHost()
```

but i got following error:

```
  File "C:\Users\lesh9198\AppData\Roaming\Python\Python35\site-packages\vix\VixHost.py", line 115, in __init__
    ffi.cast('void*', 0),
  File "C:\Users\lesh9198\AppData\Roaming\Python\Python35\site-packages\vix\VixJob.py", line 59, in __init__
    assert self.get_type() == VixHandle.VIX_HANDLETYPE_JOB, 'Expected VixJob handle.'
AssertionError: Expected VixJob handle.
```

Is that because, i don't use VMWare workstation?
