### ISSUE TITLE
wait_for_tools issue.

### ISSUE THREAD

**Issue by ghost** [naim94a/vix#5]
Hi, naim94a.
Here is a small code:

```
def main():

	host = VixHost()

	try:
		print 'Opening VM'
		vm = host.open_vm(r'blablablapath.vmx')

		print 'Getting snapshot and reverting'
		snap = vm.snapshot_get_named(r'blablablasnapname')
		vm.snapshot_revert(snap, 512)

		print 'Waiting for VMWare Tools'
		vm.wait_for_tools()
```
Output is:

> File "C:\Python27\lib\site-packages\cffi\api.py", line 281, in cast
>     cdecl = self._typeof(cdecl)
>   File "C:\Python27\lib\site-packages\cffi\api.py", line 173, in _typeof
>     "pointer-to-function type" % (cdecl,))
> cffi.api.CDefError: the type 'VixEventProc' is a function type, not a pointer-to-function type

So here is your code:

```
return vix.VixVM_WaitForToolsInGuest(
            self._handle,
            ffi.cast('int', timeout),
            ffi.cast('VixEventProc', 0),
            ffi.cast('void*', 0),
```

Dunno why, but cffi doesn't like VixEventProc type, but all we need is to pass NULL to VixVM_WaitForToolsInGuest routine. So my fix is:

```
return vix.VixVM_WaitForToolsInGuest(
            self._handle,
            ffi.cast('int', timeout),
            ffi.cast('void*', 0),
            ffi.cast('void*', 0
```

**Comment by naim94a** [comment]
Hi @MamuEbal,
Thanks for that! Fixed in commit 0416092
